language: go

go:
- 1.7
- 1.8

install:
- go get -v github.com/pkg/errors
- go get -v github.com/golang/lint/golint
- go get -v github.com/mattn/goveralls
- go get -v github.com/stretchr/testify/...
- go get -v github.com/cenkalti/backoff
- go get -v github.com/pkg/errors
- go get -v gopkg.in/jarcoal/httpmock.v1

script:
- go vet .
- golint -set_exit_status .
- go test -v -covermode=count -coverprofile=profile.cov .

after_success:
- goveralls -coverprofile=profile.cov -service=travis-ci
