sudo: required

language: go

go:
- '1.12'

services:
  - docker

addons:
  hosts:
  - localhost

env:
  global:
  - GO111MODULE=on
  - DOCKER_COMPOSE_VERSION="1.22.0"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
- docker --version
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin

install:
- git clone https://github.com/zalando/nakadi.git nakadi
- GO111MODULE=off go get github.com/alecthomas/gometalinter
- GO111MODULE=off gometalinter --install --force
- go get github.com/mattn/goveralls

before_script:
- sudo /etc/init.d/postgresql stop
- (cd nakadi && ./gradlew startNakadi)

script:
- go mod vendor -v
- GO111MODULE=off gometalinter --config=.gometalinter.json --deadline=10m .
- go test -mod=readonly -v -tags=integration -coverprofile=profile.cov ./...

after_script:
- (cd nakadi && ./gradlew stopNakadi)

after_success:
- goveralls -coverprofile=profile.cov -service=travis-ci
